//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acceemodule__
    {
        public string module { get; set; }
        public string accee { get; set; }
    }
}
