//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpointage
    {
        public string annee { get; set; }
        public string matricule { get; set; }
        public string mois { get; set; }
        public string nomprenom { get; set; }
        public string taux1 { get; set; }
        public string taux2 { get; set; }
        public string taux3 { get; set; }
    }
}
