//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendrier
    {
        public string NUM { get; set; }
        public Nullable<System.DateTime> datedu { get; set; }
        public Nullable<System.DateTime> dateau { get; set; }
        public string libelle { get; set; }
        public Nullable<System.TimeSpan> tdebLU1 { get; set; }
        public Nullable<System.TimeSpan> tdebLU2 { get; set; }
        public Nullable<System.TimeSpan> tdebLU3 { get; set; }
        public Nullable<System.TimeSpan> tfinLU1 { get; set; }
        public Nullable<System.TimeSpan> tfinLU2 { get; set; }
        public Nullable<System.TimeSpan> tfinLU3 { get; set; }
        public Nullable<System.TimeSpan> tdebMA1 { get; set; }
        public Nullable<System.TimeSpan> tdebMA2 { get; set; }
        public Nullable<System.TimeSpan> tdebMA3 { get; set; }
        public Nullable<System.TimeSpan> tfinMA1 { get; set; }
        public Nullable<System.TimeSpan> tfinMA2 { get; set; }
        public Nullable<System.TimeSpan> tfinMA3 { get; set; }
        public Nullable<System.TimeSpan> tdebME1 { get; set; }
        public Nullable<System.TimeSpan> tdebME2 { get; set; }
        public Nullable<System.TimeSpan> tdebME3 { get; set; }
        public Nullable<System.TimeSpan> tfinME1 { get; set; }
        public Nullable<System.TimeSpan> tfinME2 { get; set; }
        public Nullable<System.TimeSpan> tfinME3 { get; set; }
        public Nullable<System.TimeSpan> tdebJE1 { get; set; }
        public Nullable<System.TimeSpan> tdebJE2 { get; set; }
        public Nullable<System.TimeSpan> tdebJE3 { get; set; }
        public Nullable<System.TimeSpan> tfinJE1 { get; set; }
        public Nullable<System.TimeSpan> tfinJE2 { get; set; }
        public Nullable<System.TimeSpan> tfinJE3 { get; set; }
        public Nullable<System.TimeSpan> tdebVE1 { get; set; }
        public Nullable<System.TimeSpan> tdebVE2 { get; set; }
        public Nullable<System.TimeSpan> tdebVE3 { get; set; }
        public Nullable<System.TimeSpan> tfinVE1 { get; set; }
        public Nullable<System.TimeSpan> tfinVE2 { get; set; }
        public Nullable<System.TimeSpan> tfinVE3 { get; set; }
        public Nullable<System.TimeSpan> tdebSA1 { get; set; }
        public Nullable<System.TimeSpan> tdebSA2 { get; set; }
        public Nullable<System.TimeSpan> tdebSA3 { get; set; }
        public Nullable<System.TimeSpan> tfinSA1 { get; set; }
        public Nullable<System.TimeSpan> tfinSA2 { get; set; }
        public Nullable<System.TimeSpan> tfinSA3 { get; set; }
        public Nullable<System.TimeSpan> tdebDI1 { get; set; }
        public Nullable<System.TimeSpan> tdebDI2 { get; set; }
        public Nullable<System.TimeSpan> tdebDI3 { get; set; }
        public Nullable<System.TimeSpan> tfinDI1 { get; set; }
        public Nullable<System.TimeSpan> tfinDI2 { get; set; }
        public Nullable<System.TimeSpan> tfinDI3 { get; set; }
        public Nullable<System.TimeSpan> THLU { get; set; }
        public Nullable<System.TimeSpan> THMA { get; set; }
        public Nullable<System.TimeSpan> THME { get; set; }
        public Nullable<System.TimeSpan> THJE { get; set; }
        public Nullable<System.TimeSpan> THVE { get; set; }
        public Nullable<System.TimeSpan> THSA { get; set; }
        public Nullable<System.TimeSpan> THDI { get; set; }
        public Nullable<System.TimeSpan> TempsRepos { get; set; }
    }
}
