//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendrierold
    {
        public string NUM { get; set; }
        public Nullable<System.DateTime> datedu { get; set; }
        public Nullable<System.DateTime> dateau { get; set; }
        public string libelle { get; set; }
        public Nullable<System.TimeSpan> tempdeb1 { get; set; }
        public Nullable<System.TimeSpan> tempfin1 { get; set; }
        public Nullable<System.TimeSpan> tempdeb2 { get; set; }
        public Nullable<System.TimeSpan> tempfin2 { get; set; }
        public Nullable<System.TimeSpan> tempdeb3 { get; set; }
        public Nullable<System.TimeSpan> tempfin3 { get; set; }
    }
}
