//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnt
    {
        public string Matr { get; set; }
        public System.DateTime DateDeb { get; set; }
        public Nullable<System.DateTime> Datefin { get; set; }
        public string Libelle { get; set; }
        public string Valid { get; set; }
    }
}
