//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebptemp
    {
        public string fiche { get; set; }
        public string libelle { get; set; }
        public string annee { get; set; }
        public string mois { get; set; }
        public Nullable<int> nummois { get; set; }
        public string matricule { get; set; }
        public string nomprenom { get; set; }
        public string cnssste { get; set; }
        public string cnssempl { get; set; }
        public string categorie { get; set; }
        public string echelon { get; set; }
        public string sitf { get; set; }
        public Nullable<int> nbrenfant { get; set; }
        public string regime { get; set; }
        public string nomregime { get; set; }
        public Nullable<float> salb { get; set; }
        public string atl { get; set; }
        public string desiatl { get; set; }
        public string serv { get; set; }
        public string servdes { get; set; }
        public string qual { get; set; }
        public string qualdes { get; set; }
        public string aff { get; set; }
        public string affdes { get; set; }
        public string tit { get; set; }
        public string titdes { get; set; }
        public Nullable<float> jhtrv { get; set; }
        public Nullable<float> jcong { get; set; }
        public Nullable<float> jfer { get; set; }
        public Nullable<float> habs { get; set; }
        public Nullable<float> salbase { get; set; }
        public Nullable<float> toths { get; set; }
        public Nullable<float> totprime { get; set; }
        public Nullable<float> salbrut { get; set; }
        public Nullable<float> cnss { get; set; }
        public Nullable<float> tauxcnss { get; set; }
        public Nullable<float> salimpo { get; set; }
        public Nullable<float> impot { get; set; }
        public Nullable<float> salnet { get; set; }
        public Nullable<float> netpaye { get; set; }
        public Nullable<float> txcnss { get; set; }
        public Nullable<float> txacctrv { get; set; }
        public string deccnss { get; set; }
        public string banquesoc { get; set; }
        public string modepaie { get; set; }
        public string codeint { get; set; }
        public Nullable<float> valcong { get; set; }
        public Nullable<float> valferie { get; set; }
        public Nullable<double> autres { get; set; }
        public Nullable<double> TXCNAM { get; set; }
        public Nullable<double> TAUXCNAM { get; set; }
        public Nullable<double> CNAM { get; set; }
        public Nullable<double> totpret { get; set; }
        public string decimpot { get; set; }
        public Nullable<double> hfer { get; set; }
        public Nullable<double> hcong { get; set; }
        public Nullable<double> mtredevance { get; set; }
        public Nullable<double> tfp { get; set; }
        public Nullable<double> foprolos { get; set; }
        public string chef { get; set; }
        public Nullable<double> soldeconge { get; set; }
        public Nullable<double> impcss { get; set; }
    }
}
