//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecn
    {
        public string annee { get; set; }
        public string trimestre { get; set; }
        public float txcotss { get; set; }
        public string datearrive { get; set; }
        public string modepaye { get; set; }
        public Nullable<double> montant { get; set; }
        public string caissele { get; set; }
        public string chequedu { get; set; }
        public string banque { get; set; }
        public string virement { get; set; }
        public string mandat { get; set; }
        public Nullable<double> saldecss { get; set; }
        public Nullable<double> saldecact { get; set; }
        public Nullable<float> txcotact { get; set; }
        public Nullable<int> nbsalarie { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> montantk { get; set; }
    }
}
