//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emploi_temp
    {
        public System.DateTime datedu1 { get; set; }
        public System.DateTime dateau1 { get; set; }
        public System.DateTime datedu2 { get; set; }
        public System.DateTime dateau2 { get; set; }
        public System.TimeSpan tluds { get; set; }
        public System.TimeSpan tmads { get; set; }
        public System.TimeSpan tmeds { get; set; }
        public System.TimeSpan tjeds { get; set; }
        public System.TimeSpan tveds { get; set; }
        public System.TimeSpan tsads { get; set; }
        public System.TimeSpan tdids { get; set; }
        public System.TimeSpan ttrds { get; set; }
        public System.TimeSpan tlusu { get; set; }
        public System.TimeSpan tmasu { get; set; }
        public System.TimeSpan tmesu { get; set; }
        public System.TimeSpan tjesu { get; set; }
        public System.TimeSpan tvesu { get; set; }
        public System.TimeSpan tsasu { get; set; }
        public System.TimeSpan tdisu { get; set; }
        public System.TimeSpan ttrsu { get; set; }
        public System.TimeSpan TE11 { get; set; }
        public System.TimeSpan TE12 { get; set; }
        public System.TimeSpan TE13 { get; set; }
        public System.TimeSpan TE14 { get; set; }
        public System.TimeSpan TE15 { get; set; }
        public System.TimeSpan TE16 { get; set; }
        public System.TimeSpan TE17 { get; set; }
        public System.TimeSpan TS11 { get; set; }
        public System.TimeSpan TS12 { get; set; }
        public System.TimeSpan TS13 { get; set; }
        public System.TimeSpan TS14 { get; set; }
        public System.TimeSpan TS15 { get; set; }
        public System.TimeSpan TS16 { get; set; }
        public System.TimeSpan TS17 { get; set; }
        public System.TimeSpan TE21 { get; set; }
        public System.TimeSpan TE22 { get; set; }
        public System.TimeSpan TE23 { get; set; }
        public System.TimeSpan TE24 { get; set; }
        public System.TimeSpan TE25 { get; set; }
        public System.TimeSpan TE26 { get; set; }
        public System.TimeSpan TE27 { get; set; }
        public System.TimeSpan TS21 { get; set; }
        public System.TimeSpan TS22 { get; set; }
        public System.TimeSpan TS23 { get; set; }
        public System.TimeSpan TS24 { get; set; }
        public System.TimeSpan TS25 { get; set; }
        public System.TimeSpan TS26 { get; set; }
        public System.TimeSpan TS27 { get; set; }
        public System.TimeSpan TEE11 { get; set; }
        public System.TimeSpan TEE12 { get; set; }
        public System.TimeSpan TEE13 { get; set; }
        public System.TimeSpan TEE14 { get; set; }
        public System.TimeSpan TEE15 { get; set; }
        public System.TimeSpan TEE16 { get; set; }
        public System.TimeSpan TEE17 { get; set; }
        public System.TimeSpan TSS11 { get; set; }
        public System.TimeSpan TSS12 { get; set; }
        public System.TimeSpan TSS13 { get; set; }
        public System.TimeSpan TSS14 { get; set; }
        public System.TimeSpan TSS15 { get; set; }
        public System.TimeSpan TSS16 { get; set; }
        public System.TimeSpan TSS17 { get; set; }
        public string Code { get; set; }
        public string libelle { get; set; }
    }
}
