//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entpointage
    {
        public string codfich { get; set; }
        public string codchantier { get; set; }
        public string annee { get; set; }
        public string mois { get; set; }
        public Nullable<int> nummois { get; set; }
        public string Generer { get; set; }
    }
}
