//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grillesalaire
    {
        public string ancumule { get; set; }
        public string categorie { get; set; }
        public string durechelon { get; set; }
        public string durechelle { get; set; }
        public string echelle { get; set; }
        public string echelon { get; set; }
        public string regime { get; set; }
        public Nullable<int> salaire { get; set; }
        public Nullable<int> tauxhor { get; set; }
    }
}
