//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grpaie2Entities : DbContext
    {
        public grpaie2Entities()
            : base("name=grpaie2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<affectation> affectation { get; set; }
        public DbSet<atelier> atelier { get; set; }
        public DbSet<autrepoint> autrepoint { get; set; }
        public DbSet<banque> banque { get; set; }
        public DbSet<bpointage> bpointage { get; set; }
        public DbSet<brouillardpoint> brouillardpoint { get; set; }
        public DbSet<calendjf> calendjf { get; set; }
        public DbSet<calendrier> calendrier { get; set; }
        public DbSet<calendrierold> calendrierold { get; set; }
        public DbSet<chantier> chantier { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<cnt> cnt { get; set; }
        public DbSet<conge> conge { get; set; }
        public DbSet<ebp> ebp { get; set; }
        public DbSet<ebp_hist> ebp_hist { get; set; }
        public DbSet<ebparchive> ebparchive { get; set; }
        public DbSet<ebptemp> ebptemp { get; set; }
        public DbSet<ecn> ecn { get; set; }
        public DbSet<entpointage> entpointage { get; set; }
        public DbSet<fich> fich { get; set; }
        public DbSet<fpointage> fpointage { get; set; }
        public DbSet<grille> grille { get; set; }
        public DbSet<grillesalaire> grillesalaire { get; set; }
        public DbSet<heursupp> heursupp { get; set; }
        public DbSet<intervalle> intervalle { get; set; }
        public DbSet<lbp> lbp { get; set; }
        public DbSet<lbparchive> lbparchive { get; set; }
        public DbSet<lbptemp> lbptemp { get; set; }
        public DbSet<lcn> lcn { get; set; }
        public DbSet<lignepointage> lignepointage { get; set; }
        public DbSet<ligneprime> ligneprime { get; set; }
        public DbSet<lignerub> lignerub { get; set; }
        public DbSet<lmission> lmission { get; set; }
        public DbSet<majconge> majconge { get; set; }
        public DbSet<majconge1> majconge1 { get; set; }
        public DbSet<majpret> majpret { get; set; }
        public DbSet<mission> mission { get; set; }
        public DbSet<nbrjour> nbrjour { get; set; }
        public DbSet<nomjour> nomjour { get; set; }
        public DbSet<persarchive> persarchive { get; set; }
        public DbSet<personnel> personnel { get; set; }
        public DbSet<poijourtmp> poijourtmp { get; set; }
        public DbSet<poijourtmp1> poijourtmp1 { get; set; }
        public DbSet<pointeuse> pointeuse { get; set; }
        public DbSet<pointjour> pointjour { get; set; }
        public DbSet<pret> pret { get; set; }
        public DbSet<primepers> primepers { get; set; }
        public DbSet<qualification> qualification { get; set; }
        public DbSet<rubrique> rubrique { get; set; }
        public DbSet<service> service { get; set; }
        public DbSet<situationadmin> situationadmin { get; set; }
        public DbSet<societe> societe { get; set; }
        public DbSet<tempautrepoint> tempautrepoint { get; set; }
        public DbSet<tempcot> tempcot { get; set; }
        public DbSet<tempheursupp> tempheursupp { get; set; }
        public DbSet<templignepointage> templignepointage { get; set; }
        public DbSet<templigneprime> templigneprime { get; set; }
        public DbSet<templignerub> templignerub { get; set; }
        public DbSet<tempmajconge> tempmajconge { get; set; }
        public DbSet<ths> ths { get; set; }
        public DbSet<variable> variable { get; set; }
        public DbSet<vnote> vnote { get; set; }
        public DbSet<emploi_temp> emploi_temp { get; set; }
        public DbSet<lbp_hist> lbp_hist { get; set; }
        public DbSet<nomtable> nomtable { get; set; }
        public DbSet<trace_pointage> trace_pointage { get; set; }
    }
}
