//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lbp
    {
        public int nbr { get; set; }
        public string fiche { get; set; }
        public string annee { get; set; }
        public string mois { get; set; }
        public string matricule { get; set; }
        public string rubrique { get; set; }
        public string libelle { get; set; }
        public float nombre { get; set; }
        public float retenue { get; set; }
        public float gain { get; set; }
        public string imposable { get; set; }
        public string cotisable { get; set; }
        public string Group1 { get; set; }
    }
}
