//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lcn
    {
        public string annee { get; set; }
        public string trimestre { get; set; }
        public float txcot { get; set; }
        public string numcnss { get; set; }
        public string matricule { get; set; }
        public Nullable<double> mois1 { get; set; }
        public Nullable<double> mois2 { get; set; }
        public Nullable<double> mois3 { get; set; }
        public Nullable<int> page { get; set; }
        public Nullable<int> numerordre { get; set; }
        public string nomprenom { get; set; }
        public string categorie { get; set; }
        public Nullable<double> mois1k { get; set; }
        public Nullable<double> mois2k { get; set; }
        public Nullable<double> mois3k { get; set; }
        public Nullable<int> sel { get; set; }
    }
}
