//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligneprime
    {
        public string rubrique { get; set; }
        public string designarub { get; set; }
        public Nullable<float> montant { get; set; }
        public string matr { get; set; }
        public string confirme { get; set; }
        public string fiche { get; set; }
        public string libelle { get; set; }
        public long nligne { get; set; }
    }
}
