//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lmission
    {
        public string nummission { get; set; }
        public string codeemp { get; set; }
        public string libemp { get; set; }
        public string codequal { get; set; }
        public string libqual { get; set; }
        public Nullable<double> num { get; set; }
    }
}
