//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class majpret
    {
        public string code { get; set; }
        public string designa { get; set; }
        public Nullable<System.DateTime> date1ret { get; set; }
        public System.DateTime datepret { get; set; }
        public string blocage { get; set; }
        public string matricule { get; set; }
        public string nomprenom { get; set; }
        public Nullable<float> montret { get; set; }
        public Nullable<float> montpret { get; set; }
        public Nullable<float> montrest { get; set; }
        public string fiche { get; set; }
        public string desifich { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public Nullable<System.DateTime> datef { get; set; }
        public Nullable<float> MontInit { get; set; }
    }
}
