//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mission
    {
        public string nummission { get; set; }
        public Nullable<System.DateTime> datesortie { get; set; }
        public Nullable<System.DateTime> dateretour { get; set; }
        public string numao { get; set; }
        public Nullable<double> nbjour { get; set; }
        public string projet { get; set; }
        public string lieuint { get; set; }
        public string codecli { get; set; }
        public string rscli { get; set; }
        public string perscontac { get; set; }
        public string codsui { get; set; }
        public string dessui { get; set; }
        public string description { get; set; }
        public string coddemand { get; set; }
        public string libdemand { get; set; }
        public string compterendu { get; set; }
        public string generer { get; set; }
        public string heurrdv { get; set; }
        public string typeint { get; set; }
        public string nbhest { get; set; }
        public Nullable<int> cloture { get; set; }
    }
}
