//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel
    {
        public string MATR { get; set; }
        public string CAISSE { get; set; }
        public string ECHELON { get; set; }
        public string PAYEMENT { get; set; }
        public string NATIONAL { get; set; }
        public Nullable<int> TRV_AN { get; set; }
        public string NOMPRENOM1 { get; set; }
        public string PRENOM1 { get; set; }
        public string PRENOM2 { get; set; }
        public string PRENOM3 { get; set; }
        public string PRENOM4 { get; set; }
        public Nullable<int> NBRENFANT { get; set; }
        public string CIN { get; set; }
        public string NUMCNSS { get; set; }
        public string SERV { get; set; }
        public string REGIME2 { get; set; }
        public string REGIME1 { get; set; }
        public string nomregime1 { get; set; }
        public Nullable<float> SALB { get; set; }
        public string TIT { get; set; }
        public string SITF { get; set; }
        public Nullable<float> TXHOR { get; set; }
        public Nullable<float> TXCNSS { get; set; }
        public string TELEPHONE { get; set; }
        public string NOMPRENOM2 { get; set; }
        public string BANQUESTE { get; set; }
        public string BANQUEPER { get; set; }
        public string numcompte { get; set; }
        public string DECIMPOT { get; set; }
        public Nullable<int> ARR1 { get; set; }
        public string COMPTEC { get; set; }
        public string ATELIER { get; set; }
        public string ADRESSE { get; set; }
        public string CAT { get; set; }
        public string CHEF { get; set; }
        public string PRESENCE { get; set; }
        public string QUAL { get; set; }
        public string AFF { get; set; }
        public string SEXE { get; set; }
        public Nullable<System.DateTime> DATECHE { get; set; }
        public Nullable<System.DateTime> PROCHEECHE { get; set; }
        public Nullable<System.DateTime> EMBO { get; set; }
        public Nullable<System.DateTime> NAIS { get; set; }
        public string ACCtrv { get; set; }
        public Nullable<System.DateTime> DATESIT { get; set; }
        public string NAIS1 { get; set; }
        public string NAIS2 { get; set; }
        public string NAIS3 { get; set; }
        public string NAIS4 { get; set; }
        public string imagepersonnel { get; set; }
        public string SMIG { get; set; }
        public string SUPH { get; set; }
        public Nullable<System.DateTime> DATECIN { get; set; }
        public Nullable<double> SoldInit { get; set; }
        public Nullable<double> DroitCong { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> assurance { get; set; }
        public string matpointeuse { get; set; }
        public string redevance { get; set; }
        public Nullable<double> nbmois { get; set; }
        public double tfp { get; set; }
        public Nullable<double> foprolos { get; set; }
        public Nullable<double> comptecb { get; set; }
        public string sel { get; set; }
        public Nullable<System.DateTime> DateDepart { get; set; }
        public string imagepath { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> imagesize { get; set; }
        public string email { get; set; }
    }
}
