//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poijourtmp
    {
        public string codfich { get; set; }
        public string codchan { get; set; }
        public string annee { get; set; }
        public string mois { get; set; }
        public string matricule { get; set; }
        public string j1 { get; set; }
        public string j2 { get; set; }
        public string j3 { get; set; }
        public string j4 { get; set; }
        public string j5 { get; set; }
        public string j6 { get; set; }
        public string j7 { get; set; }
        public string j8 { get; set; }
        public string j9 { get; set; }
        public string j10 { get; set; }
        public string j11 { get; set; }
        public string j12 { get; set; }
        public string j13 { get; set; }
        public string j14 { get; set; }
        public string j15 { get; set; }
        public string j16 { get; set; }
        public string j17 { get; set; }
        public string j18 { get; set; }
        public string j19 { get; set; }
        public string j20 { get; set; }
        public string j21 { get; set; }
        public string j22 { get; set; }
        public string j23 { get; set; }
        public string j24 { get; set; }
        public string j25 { get; set; }
        public string j26 { get; set; }
        public string j27 { get; set; }
        public string j28 { get; set; }
        public string j29 { get; set; }
        public string j30 { get; set; }
        public string j31 { get; set; }
        public Nullable<double> totheure { get; set; }
        public Nullable<double> totjour { get; set; }
        public string type { get; set; }
    }
}
