//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pointeuse
    {
        public string code_machine { get; set; }
        public string libelle_machine { get; set; }
        public string frs_pointeuse { get; set; }
        public string nom_base { get; set; }
        public string nom_tab_pointage { get; set; }
        public string temp_pointage { get; set; }
        public string nom_tab_personnel { get; set; }
        public string code_personnel { get; set; }
        public string nom_personnel { get; set; }
        public string pre_personnel { get; set; }
        public string cheminbd { get; set; }
        public string type_code_utilisateur { get; set; }
        public string type_base { get; set; }
        public string defaut { get; set; }
        public string correction_p { get; set; }
        public string nbr_seance { get; set; }
        public string IP_Machine { get; set; }
        public string Port_Machine { get; set; }
        public string ID_Machine { get; set; }
        public string EmpStd { get; set; }
        public string type_pointage { get; set; }
    }
}
