//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class societe
    {
        public string CODSOC { get; set; }
        public string NOMSOCI { get; set; }
        public string ADRESSE { get; set; }
        public string NBUREAU { get; set; }
        public string CODETVA { get; set; }
        public string CODPOSTAL { get; set; }
        public string CODUSE { get; set; }
        public string DATCLOT { get; set; }
        public string DIRECTEUR { get; set; }
        public Nullable<float> FOPROLOS { get; set; }
        public string NUMCNSS { get; set; }
        public Nullable<float> TFP { get; set; }
        public Nullable<float> ACCTRV { get; set; }
        public Nullable<float> TXEMPLOYEUR { get; set; }
        public Nullable<float> TXEMPLOYER { get; set; }
        public string TELEFAX { get; set; }
        public string TELEX { get; set; }
        public string TELEPHONE { get; set; }
        public string VILLE { get; set; }
        public string MODELE { get; set; }
        public float TXARRONDI { get; set; }
        public string TYPEIRPP { get; set; }
        public Nullable<float> jnormal { get; set; }
        public Nullable<float> hnormal { get; set; }
        public string clotfiches { get; set; }
    }
}
