//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class societe
    {
        public string CODSOC { get; set; }
        public string NOMSOCI { get; set; }
        public string ADRESSE { get; set; }
        public string NBUREAU { get; set; }
        public string CODETVA { get; set; }
        public string CODPOSTAL { get; set; }
        public string CODUSE { get; set; }
        public string DATCLOT { get; set; }
        public string DIRECTEUR { get; set; }
        public Nullable<float> FOPROLOS { get; set; }
        public string NUMCNSS { get; set; }
        public Nullable<float> TFP { get; set; }
        public Nullable<float> ACCTRV { get; set; }
        public Nullable<float> TXEMPLOYEUR { get; set; }
        public Nullable<float> TXEMPLOYER { get; set; }
        public string TELEFAX { get; set; }
        public string TELEX { get; set; }
        public string TELEPHONE { get; set; }
        public string VILLE { get; set; }
        public string MODELE { get; set; }
        public float TXARRONDI { get; set; }
        public string TYPEIRPP { get; set; }
        public Nullable<float> jnormal { get; set; }
        public Nullable<float> hnormal { get; set; }
        public string clotfiches { get; set; }
        public Nullable<double> CNAMEMPLOYEUR { get; set; }
        public Nullable<double> CNAMEMPLOYE { get; set; }
        public string hortra { get; set; }
        public string GUTIL { get; set; }
        public string chantier { get; set; }
        public Nullable<int> nbrmois { get; set; }
        public string pointrub { get; set; }
        public Nullable<double> nbrheure { get; set; }
        public string disquetcnss { get; set; }
        public string suppbanque { get; set; }
        public string liaison_pointeuse { get; set; }
        public Nullable<double> mtredevance { get; set; }
        public string txredevance { get; set; }
        public string parampoint { get; set; }
        public string Synchronisation { get; set; }
        public string majred { get; set; }
        public string impotshs { get; set; }
        public string sdconj { get; set; }
        public string ParamRappel { get; set; }
        public string calhmens { get; set; }
        public string enthpoint { get; set; }
        public string calmmens { get; set; }
        public string sortcal { get; set; }
        public string rue { get; set; }
        public string activite { get; set; }
        public string numero { get; set; }
        public string exercice { get; set; }
        public string codeacte { get; set; }
        public string TMAJO { get; set; }
        public string mf { get; set; }
        public string ParamAnn1 { get; set; }
    }
}
