//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class templignerub
    {
        public string codrubrique { get; set; }
        public string condition { get; set; }
        public string Formule { get; set; }
        public string confirme { get; set; }
        public int ligne { get; set; }
        public Nullable<double> plafond { get; set; }
    }
}
