//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempheursupp
    {
        public string codheursupp { get; set; }
        public Nullable<int> taux { get; set; }
        public string libelle { get; set; }
        public Nullable<float> nbrheursupp { get; set; }
        public string codfich { get; set; }
        public string codchantier { get; set; }
        public string annee { get; set; }
        public string mois { get; set; }
        public string matr { get; set; }
        public string nomprenom { get; set; }
        public string confirme { get; set; }
    }
}
