//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempmajconge
    {
        public string code { get; set; }
        public string libelle { get; set; }
        public string type { get; set; }
        public Nullable<float> nbrjour { get; set; }
        public Nullable<float> nbrheure { get; set; }
        public string matricule { get; set; }
        public string nomprenom { get; set; }
        public Nullable<float> solde { get; set; }
        public string datedepart { get; set; }
        public string datefin { get; set; }
        public string payer { get; set; }
    }
}
