//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ths
    {
        public string codths { get; set; }
        public string libelle { get; set; }
        public Nullable<int> taux { get; set; }
        public string regime { get; set; }
        public double MtSupp { get; set; }
    }
}
