//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp
    {
        public int N_ { get; set; }
        public string module { get; set; }
        public string accee { get; set; }
        public string societe { get; set; }
        public string ajouter { get; set; }
        public string SUPPRIMER { get; set; }
        public string MODIFIER { get; set; }
    }
}
