//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trace_pointage
    {
        public System.DateTime Ancien_date { get; set; }
        public string Ancien_time { get; set; }
        public System.DateTime nouv_date { get; set; }
        public string nouv_time { get; set; }
        public string matricule { get; set; }
        public string Nom_Pre { get; set; }
        public System.DateTime date_maj { get; set; }
        public string temp_maj { get; set; }
        public string operation { get; set; }
        public string user { get; set; }
    }
}
