//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userpaieEntities : DbContext
    {
        public userpaieEntities()
            : base("name=userpaieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<couleur> couleur { get; set; }
        public DbSet<importation> importation { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<menumotdepasse> menumotdepasse { get; set; }
        public DbSet<paramaitre> paramaitre { get; set; }
        public DbSet<size> size { get; set; }
        public DbSet<societe> societe { get; set; }
        public DbSet<tmp> tmp { get; set; }
        public DbSet<usersoc> usersoc { get; set; }
        public DbSet<utilisateur> utilisateur { get; set; }
        public DbSet<utilitaire> utilitaire { get; set; }
        public DbSet<acceemodule__> acceemodule__ { get; set; }
        public DbSet<nomtable> nomtable { get; set; }
    }
}
