//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public string compteuser { get; set; }
        public string motdepasse { get; set; }
        public string DERSOC { get; set; }
        public string actif { get; set; }
        public string numvol { get; set; }
        public string type { get; set; }
    }
}
