//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaieBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vnote
    {
        public string matricule { get; set; }
        public string annee { get; set; }
        public string mois { get; set; }
        public Nullable<float> note_rend { get; set; }
        public Nullable<int> note_prod { get; set; }
        public string nomprenom { get; set; }
    }
}
